id: DE28559FB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-01-06T09:34:21+00:00'
last_modified: '2022-05-26T14:15:08.329232+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    fe44:
      image_group_id: I1PD95885
      title: སྒྲོལ་མའི་རྟོག་པ་ལས་འབྱུང་བའི་ཚིག་ལྷུག་པའི་རིགས་བྱེད་མའི་སྒྲུབ་ཐབས།
      total_pages: 1648
      order: 40
      base_file: fe44.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
